#!/usr/bin/env python3
import sys, os, json
from pathlib import Path
args=sys.argv[1:]
for i,a in enumerate(args):
    if a in ('-j','--build-jobs'):
        args[i+1]='8'
    elif a.startswith('-j') and a[2:].isdigit():
        args[i]='-j8'
with (Path(__file__).parent/'verilator-invocations.jsonl').open('a') as f:
    f.write(json.dumps({'cwd':os.getcwd(),'argv':['/usr/bin/verilator']+args})+'\n')
os.execv('/usr/bin/verilator',['/usr/bin/verilator']+args)
