#!/usr/bin/env python3
import os,sys,subprocess,json,pathlib
args=sys.argv[1:]; effective=[]; i=0
while i<len(args):
    if args[i] in ('-j','--build-jobs'):
        effective += [args[i],'8']; i+=2
    elif args[i].startswith('-j') and args[i][2:].isdigit():
        effective += ['-j8']; i+=1
    else:
        effective.append(args[i]); i+=1
p=pathlib.Path(os.environ['R229_RECEIPTS'])
with (p/'verilator-invocations.jsonl').open('a') as f:
    f.write(json.dumps({'probe':os.environ.get('R229_PROBE'), 'cwd':os.getcwd(),'requested':args,'effective':effective})+'\n')
raise SystemExit(subprocess.call(['/usr/bin/verilator',*effective]))
